/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface City {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<Int8>;
  name: string;
  stateId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface Country {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<Int8>;
  iso3: string;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface State {
  countryId: Int8;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<Int8>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  cities: City;
  countries: Country;
  states: State;
}
