#!/usr/bin/env sh
set -e

# Check if there are staged changes
if git diff --cached --quiet; then
  printf "\033[33mNo staged changes found.\033[0m\n"
  exit 0
fi

if [ "$CI" = "true" ]; then
  exit 0
fi

# Run commitizen prompt
exec < /dev/tty && node_modules/.bin/cz --hook || true
